In [3]:
# Maaf Pak, yang sebelumnya salah upload, malah mengupload yang sesi 3
# Soal 1
import numpy as np

mulai = int(input("Mulai: "))
selesai = int(input("Selesai: "))

arr = np.arange(mulai, selesai)
print("Array 1 dimensi: ")
print(arr)

arr2 = arr.reshape(3, 9)
print("Array 2 dimensi: ")
print(arr2)

arr3 = arr.reshape(3, 3, 3)
print("Array 3 dimensi: ")
print(arr3)

Mulai: 1
Selesai: 28
Array 1 dimensi: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
Array 2 dimensi: 
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
Array 3 dimensi: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [29]:
# Soal 2
import numpy as np

n = int(input("Banyak data (harus kelipatan 3): "))
mulai = int(input("Mulai: "))
selesai = int(input("Selesai: "))

arr = np.random.randint(mulai,selesai,(n))
print("Array 1 dimensi:")
print(arr)
    
arr2 = arr.reshape(3, int(n/3))
print("Array 2 dimensi:")
print(arr2)

arr3 = arr2[:, ::-1]
print("Flip array:")
print(arr3)

Banyak data (harus kelipatan 3): 18
Mulai: 1
Selesai: 50
Array 1 dimensi:
[41 40  9  6 45 43 31 23 45 49 33 49 20  3  6 46  5 46]
Array 2 dimensi:
[[41 40  9  6 45 43]
 [31 23 45 49 33 49]
 [20  3  6 46  5 46]]
Flip array:
[[43 45  6  9 40 41]
 [49 33 49 45 23 31]
 [46  5 46  6  3 20]]


In [25]:
# Soal 3
import numpy as np

arr = np.zeros((10,10))
arr += 4
arr[1:-1,1:-1] = 0

print(arr)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
